Flipmart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('admin/', include("siteadmin.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views
app_name = 'user'

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("shop/", views.shop, name="shop"),
    path("shop/search/", views.search, name="search"),
    path("shop/category/<int:id>", views.category, name="category"),
    path("product/<int:id>", views.product, name="product"),
    path("product/<int:id>/delete_review", views.delete_review, name="delete_review"),
    path("checkout/", views.checkout, name="checkout"),
    path("contact/", views.contact, name="contact"),
    path("cart/", views.cart, name="cart"),
    path("add_to_cart/<int:id>", views.add_to_cart, name="add_to_cart"),
    path("cart/delete/<int:id>", views.delete_from_cart, name="delete_from_cart"),
    path("logout/", views.logout, name="logout"),
    path("account/", views.account, name="account"),
    path("account/delete/<int:id>", views.delete_account, name="delete_account"),
    path("checkout/complete/", views.checkout_complete, name="checkout_complete"),
    path("categories/", views.categories, name="categories"),
    path("buy_now/<int:id>", views.buy_now, name="buy_now"),
    
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from siteadmin.models import User,Product,CartItem,Category,Purchase,Review
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Avg

def get_user(request):
    try:
        user = User.objects.get(name = request.session.get('username'))
        return user
    except ObjectDoesNotExist:
        return None
    

def pass_user_details(request, context):
    """takes username from request.session and passes to context

    Args:
        request (HttpRequest): an incoming request from the user that contains session info
        context (dict): a dict that is passed to the webpage when rendering
    """
    username = request.session.get('username')
    context['username'] = username
    user = User.objects.filter(name = username).first()
    cart_items_count = CartItem.objects.filter(user = user).count()
    context['cart_items_count'] = cart_items_count


# Create your views here.
def home(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    context = {
        'categories': categories,
        'products': products
    }
    pass_user_details(request, context)
    return render(request,'user/home.html', context)

def register(request):
    # Initializing outside of form submission for first load
    register_success = False
    request_sent = False
    reasons = []
    context = {
        'register_success': register_success,
        'request_sent': request_sent,
    }
    if request.method == 'POST':
        request_sent = True
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        try:
            User.objects.create(
                name = name,
                email = email,
                password = password
            )
            register_success = True
        except IntegrityError:
            reasons.append('Username already in use')
            register_success = False
    context['register_success'] = register_success
    context['request_sent'] = request_sent
    context['reasons'] = reasons
    pass_user_details(request, context)
    return render(request, 'user/register.html', context)

def login(request):
    # Initializing outside of form submission for first load
    login_success = False
    request_sent = False
    context = {
        'login_success': login_success,
        'request_sent': request_sent
    }
    if request.method == 'POST':
        request_sent = True
        name = request.POST['name']
        password = request.POST['password']

        user = User.objects.filter(name=name, password=password) # Returns an queryset object
        if user.exists():
            login_success = True
            request.session['username'] = user.first().name
            return redirect('user:home')
        else:
            login_success = False
        
    context['login_success'] = login_success
    context['request_sent'] = request_sent
    pass_user_details(request, context)
    return render(request, 'user/login.html', context)


def logout(request):
    if request.session.get('username') != None:
        del request.session['username']
    return redirect('user:home')


def shop(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    pass_user_details(request, context)
    return render(request, 'user/shop.html', context)


def search(request):
    if request.method == 'POST':
        search_term = request.POST['search_term']
        products = Product.objects.filter(name__icontains = search_term)
    else:
        return redirect('user:shop')
    context = {
        'products': products,
        'search_term': search_term
    }
    pass_user_details(request, context)
    return render(request, 'user/shop.html', context)

def category(request, id):
    products = Product.objects.filter(category = id)
    category = Category.objects.get(id = id)
    context = {
        'products': products,
        'category': category.name
    }
    pass_user_details(request, context)
    return render(request, 'user/shop.html', context)


def categories(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }
    pass_user_details(request, context)
    return render(request,'user/categories.html', context)


def product(request, id):
    product = Product.objects.get(id = id)
    reviews = Review.objects.filter(product = product)
    if reviews.exists():
        avg_rating = round(reviews.aggregate(Avg("rating"))['rating__avg'], ndigits=1)
    else:
        avg_rating = 'N/A'
    
    # Pass as iterable?
    rating_1 = reviews.filter(rating = 1).count()
    rating_2 = reviews.filter(rating = 2).count()
    rating_3 = reviews.filter(rating = 3).count()
    rating_4 = reviews.filter(rating = 4).count()
    rating_5 = reviews.filter(rating = 5).count()
    context = {
        'product': product,
        'reviews': reviews,
        'avg_rating': avg_rating,
        'rating_1': rating_1,
        'rating_2': rating_2,
        'rating_3': rating_3,
        'rating_4': rating_4,
        'rating_5': rating_5
    }
    # People should be able to view products without logging in!!!!
    user = get_user(request)
    if user == None:
        return redirect('user:login')
    purchases = Purchase.objects.filter(user = user, product=product)
    userreview = Review.objects.filter(user=user, product=product)
    context.update({'userreview': userreview.first()})
    purchased_product = False
    reviewed = False
    if purchases.exists():
        purchased_product = True
    if userreview.exists():
        reviewed = True
    context.update({'purchased_product': purchased_product})
    context.update({'reviewed': reviewed})
    if request.method == 'POST' and request.POST['action'] == 'Add Review':
        details = request.POST['details']
        rating = request.POST['rating']
        
        Review.objects.create(
            user = user,
            rating = rating,
            details = details,
            product = product
        )
        return redirect('user:product', product.id)
    
    elif request.method == 'POST' and request.POST['action'] == 'Edit Review':
        details = request.POST['details']
        rating = request.POST['rating']
        userreview.update(
            details = details,
            rating = rating
        )
        return redirect('user:product', product.id)

    products = Product.objects.filter(category = product.category)
    context['products'] = products
    pass_user_details(request, context)
    return render(request, 'user/product.html', context)


def delete_review(request, id):
    user = get_user(request)
    if user == None:
        return redirect('user:login')
    product = Product.objects.get(id = id)
    userreview = Review.objects.filter(user=user, product=product)
    userreview.delete()
    return redirect('user:product', product.id)

def checkout(request):
    user = get_user(request)
    if user == None:
        return redirect('user:login')
    cart_items = CartItem.objects.filter(user = user)
    subtotal = 0
    for cart_item in cart_items:
        cart_item.total = cart_item.product.price * cart_item.quantity
        subtotal += cart_item.product.price * cart_item.quantity

    shipping = 50
    total = subtotal + shipping
    context = {
        'user': user,
        'cart_items': cart_items,
        'subtotal': subtotal,
        'shipping': shipping,
        'total': total
    }
    # User completes payment
    if request.method == 'POST':
        for cart_item in cart_items:
            # Create purchase record
            Purchase.objects.create(
                product = cart_item.product,
                quantity = cart_item.quantity,
                user = cart_item.user
            )
            # Remove from cart
            cart_item.delete()
        return redirect('user:checkout_complete')
    
    pass_user_details(request, context)
    return render(request, 'user/checkout.html', context)

def checkout_complete(request):
    context = {}
    pass_user_details(request, context)
    return render(request, 'user/checkout_complete.html', context)

def contact(request):
    context = {}
    pass_user_details(request, context)
    return render(request, 'user/contact.html', context)


def buy_now(request, id):
    user = get_user(request)
    if user == None:
        return redirect('user:login')
    product = Product.objects.get(id = id)
    # Clear user's cart
    CartItem.objects.filter(user = user).delete()
    # Form input from product page
    qty = 1
    if request.method == 'POST':
        qty = request.POST['qty']

    # Add product to it
    CartItem.objects.create(
        product = product,
        quantity = qty,
        user = user
    )
    return redirect('user:checkout')


def add_to_cart(request, id):
    product = Product.objects.get(id = id)
    user = get_user(request)
    if user == None:
        return redirect('user:login')
    try:
        # This item already exists in user's cart
        cart_item = CartItem.objects.get(product = product, user = user)
        # Product page button selection managed here
        if request.method == 'POST':
            action = request.POST['action']
            if action == 'Buy Now':
                return buy_now(request, id)
            # Product page quantity input handled here
            cart_item.quantity = request.POST['qty']
        else:
            cart_item.quantity += 1
        cart_item.save()

    # This item is not in user's cart
    except ObjectDoesNotExist:
        # User input value from product page
        if request.method == 'POST':
            action = request.POST['action']
            if action == 'Buy Now':
                return buy_now(request, id)
            qty = request.POST['qty']
        else:

templates/user/account.html
{% extends 'user/home.html' %}
{% block homelink %}{% endblock %}
{% block title %}Account{% endblock %}
{% block content %}
<!-- ================ start banner area ================= -->	
<section class="blog-banner-area" id="category">
    <div class="container h-100">
        <div class="blog-banner">
            <div class="text-center">
                <h1>Account</h1>
            </div>
        </div>
</div>
</section>
<!-- ================ end banner area ================= -->
<h2 class="text-center my-5">Change Details</h2>
<form action="" method="post" class="container w-50 mb-5">
    {% csrf_token %}
    <div class="mb-3">
        <label for="" class="form-label">Username</label>
        <input type="text" name="name" value="{{user.name}}" class="form-control">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Email</label>
        <input type="text" name="email" value="{{user.email}}" class="form-control">
    </div>
    <div class="mb-3">
        <label for="" class="form-label">Password</label>
        <input type="password" name="password" value="{{user.password}}" id="showpassbox" class="form-control">
        <input type="checkbox" onclick="passwordVisibility()">
        <label for="">Show Password</label>
        <script>
            function passwordVisibility(){
                var checkbox = document.getElementById("showpassbox")
                if (checkbox.type == "password"){
                    checkbox.type = "text"
                }
                else {
                    checkbox.type = "password"
                }
            }
        </script>
    </div class="mb-3">

    <input type="submit" class="btn btn-outline-primary">
    <br>
    <a href="{% url 'user:delete_account' user.id %}" class="btn btn-outline-danger my-2">Delete Account</a>
</form>
<section>
    <h2 class="text-center mb-3">Purchase History</h2>
    <table class="table table-hover w-50 mx-auto">
        <tr>
            <th colspan="2">Product</th>
            <th>Quantity</th>
            <th>Date</th>
        </tr>
        {% for purchase in purchases %}
        <tr>
            <td>{{purchase.product}}</td>
            <td><img src="{{purchase.product.image.url}}" alt="product image" width="100" height="100"></td>
            <td>{{purchase.quantity}}</td>
            <td>{{purchase.date}}</td>
        </tr>
        {% endfor %}
    </table>
</section>
{% endblock content %}

templates/user/categories.html
{% extends 'user/home.html' %}
{% block homelink %}{% endblock %}
{% block categorylink %}active{% endblock %}
{% block title %}Categories{% endblock %}
{% block content %}
<!-- ================ start banner area ================= -->	
<section class="blog-banner-area" id="category">
    <div class="container h-100">
        <div class="blog-banner">
            <div class="text-center">
                <h1>Categories</h1>
            </div>
        </div>
</div>
</section>
<!-- ================ end banner area ================= -->
<!-- ================ Best Selling item  carousel ================= --> 
<section class="section-margin calc-60px">
    <div class="container">
      <div class="owl-carousel owl-theme" id="bestSellerCarousel">
        {% for category in categories %}
        <div class="card text-center card-product">
          <div class="card-product__img">
            <img src="{{category.image.url}}" alt="" height="250px">
            <ul class="card-product__imgOverlay">
              <li>
                <a href="{% url 'user:category' category.id %}">
                  <button class="rounded"><span class="" style="font-size: 1.5rem;">{{category.name}}</span></button>
                </a>
              </li>
            </ul>
          </div>
          <div class="card-body">
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!-- ================ Best Selling item  carousel end ================= --> 
{% endblock content %}

templates/user/checkout_complete.html
{% extends 'user/home.html' %}
{% block homelink %}{% endblock %}
{% block title %}Payment Complete{% endblock %}
{% block content %}
<!-- ================ start banner area ================= -->	
<section class="blog-banner-area" id="category">
    <div class="container h-100">
        <div class="blog-banner">
            <div class="text-center">
                <h1>Payment Complete!</h1>
                <a href="{% url 'user:shop' %}" class="btn btn-primary mt-3">Back To Products</a>
            </div>
        </div>
</div>
</section>
<!-- ================ end banner area ================= -->
{% endblock %}

templates/user/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Home{% endblock %}</title>
  <link rel="icon" href="{% static 'img/Fevicon.png' %}" type="image/png">
  <link rel="stylesheet" href="{% static 'vendors/bootstrap/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/fontawesome/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'vendors/themify-icons/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/nice-select/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  {% block header %}
  <!--================ Start Header Menu Area =================-->
	<header class="header_area">
    <div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand logo_h" href="{% url 'user:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
            <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
              <li class="nav-item {% block homelink %}active{% endblock%}"><a class="nav-link" href="{% url 'user:home' %}">Home</a></li>
              <li class="nav-item {% block shoplink %}{% endblock%}"><a class="nav-link" href="{% url 'user:shop' %}">Shop</a></li>
              <li class="nav-item {% block categorylink %}{% endblock%}"><a class="nav-link" href="{% url 'user:categories' %}">Categories</a></li>
              <li class="nav-item {% block contactlink %}{% endblock contactlink %}"><a class="nav-link" href="{% url 'user:contact' %}">Contact</a></li>
            </ul>

            <ul class="nav-shop">
              {% if not username %}
              <li class="nav-item"><a class="button button-header" href="{% url 'user:login' %}">Login</a></li>
              <li class="nav-item" style="margin: 0;"><a class="button button-header" href="{% url 'user:register' %}">Register</a></li>
              {% else %}
              <li>Hello {{username}}</li>
              <li class="nav-item"><a href="{% url 'user:cart' %}"><button><i class="ti-shopping-cart"></i><span class="nav-shop__circle">{{cart_items_count}}</span></button></a></li>
              <li class="nav-item"><a href="{% url 'user:account' %}"><i class="ti-user"></i></a> </li>
              <li class="nav-item"><a class="button button-header" href="{% url 'user:logout' %}">Logout</a></li> 
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </header>
	<!--================ End Header Menu Area =================-->
  {% endblock %}
  {% block content %}
  <main class="site-main">
    <!--================ Hero banner start =================-->
    <section class="hero-banner">
      <div class="container">
        <div class="row no-gutters align-items-center pt-60px">
          <div class="col-5 d-none d-sm-block">
            <div class="hero-banner__img">
              <img class="img-fluid" src="{% static 'img/home/hero-banner.png' %}" alt="">
            </div>
          </div>
          <div class="col-sm-7 col-lg-6 offset-lg-1 pl-4 pl-md-5 pl-lg-0">
            <div class="hero-banner__content">
              <h4>Welcome to,</h4>
              <h1>Flipmart</h1>
              <p>
                With more than 1000+ products, we aim to provide you the luxury of choice,
                right to your doorstep. Take a quick look now!
              </p>
              <a class="button button-hero" href="{% url 'user:shop' %}">Browse Now</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================ Hero banner start =================-->

    <!--================ Hero Carousel start =================-->
    <section class="section-margin my-0">
      <div class="owl-carousel owl-theme hero-carousel">
        {% for category in categories %}
        <div class="hero-carousel__slide">
          <img src="{{category.image.url}}" alt="" width="400" height="300" style="object-fit: cover;">
          <a href="{% url 'user:category' category.id %}" class="hero-carousel__slideOverlay">
            <h3>{{category.name}}</h3>
          </a>
        </div>
        {% endfor %}
      </div>
    </section>
    <!--================ Hero Carousel end =================-->
    <!-- ================ offer section start ================= --> 
    <section class="offer" id="parallax-1" data-anchor-target="#parallax-1" data-300-top="background-position: 20px 30px" data-top-bottom="background-position: 0 20px">
      <div class="container">
        <div class="row">
          <div class="col-xl-5">
            <div class="offer__content text-center">
              <h3>Up To 50% Off</h3>
              <h4>Winter Sale</h4>
              <a class="button button--active mt-3 mt-xl-4" href="{% url 'user:shop' %}">Shop Now</a>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- ================ offer section end ================= --> 

    <!-- ================ Best Selling item  carousel ================= --> 
    <section class="section-margin calc-60px">
      <div class="container">
        <div class="section-intro pb-60px">
          <p>Popular Items Today</p>
          <h2>Best <span class="section-intro__style">Sellers</span></h2>
        </div>
        <div class="owl-carousel owl-theme" id="bestSellerCarousel">
          {% for product in products %}
          <div class="card text-center card-product">
              <div class="card-product__img">
                <img class="card-img" src="{{product.image.url}}" alt="Product image" height="250px" width="250px">
                <ul class="card-product__imgOverlay">
                  <li><a href="{% url 'user:add_to_cart' product.id %}"><button onclick="addedToCart()"><i class="ti-shopping-cart"></i></button></a></li>
                  <script>
                    function addedToCart(){
                      alert('This item was added to your cart')
                    }
                  </script>
                  <li><a href="{% url 'user:buy_now' product.id %}"><button onclick="buyNow()"><i class="ti-credit-card"></i></button></a></li>
                  <script>
                    function buyNow(){
                      alert('This will remove other items from your cart')
                    }
                  </script>
                </ul>
              </div>
              <div class="card-body">
                <a href="{% url 'user:category' product.category.id %}">{{product.category.name}}</a>
                <h4 class="card-product__title"><a href="{% url 'user:product' product.id %}">{{product.name}}</a></h4>
                <p class="card-product__price">${{product.price}}</p>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </section>
    <!-- ================ Best Selling item  carousel end ================= --> 
  </main>
  {% endblock %}

  {% block footer %}
  <!--================ Start footer Area  =================-->	
	<footer class="footer">
		<div class="footer-area">
			<div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title large_title">Our Mission</h4>
							<p>
								To provide the largest range of products directly to your doorstep
                with the most convenience possible
							</p>
							<p>
								Our goal as a sustainable business is to provide for all of Earth's
                inhabitants.
							</p>
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Contact Us</h4>
							<div class="ml-40">
								<p class="sm-head">
									<span class="fa fa-location-arrow"></span>
									Head Office
								</p>
								<p>3rd Floor Josh Towers,<br>
                  Civil Line Rd, Padamughal,<br>
                  Kakkanad, Kochi, Kerala<br>
                  
                  682030</p>
	
								<p class="sm-head">
									<span class="fa fa-phone"></span>
									Phone Number
								</p>
								<a href="tel:+917845128956">
									+917845128956
                </a>
								<p class="sm-head">
									<span class="fa fa-envelope"></span>
									Email
								</p>
								<a href="mailto:contact@flipmart.com">contact@flipmart.com</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row d-flex">
					<p class="col-lg-12 footer-text text-center">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				</div>
			</div>
		</div>
	</footer>
	<!--================ End footer Area  =================-->
  {% endblock %}


  <script src="{% static 'vendors/jquery/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'vendors/bootstrap/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendors/skrollr.min.js' %}"></script>
  <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'vendors/nice-select/jquery.nice-select.min.js' %}"></script>
  <script src="{% static 'vendors/jquery.ajaxchimp.min.js' %}"></script>
  <script src="{% static 'vendors/mail-script.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/user/shop.html
{% extends 'user/home.html' %}
{% block homelink %}{% endblock %}
{% block shoplink %}active{% endblock %}
{% block title %}Shop{% endblock %}
{% block content %}
<!-- ================ start banner area ================= -->	
<section class="blog-banner-area" id="category">
    <div class="container h-100">
        <div class="blog-banner">
            <div class="text-center">
                {% if category %}
                <h1>{{category}}</h1>
                {% elif search_term %}
                <h1>You searched for: {{search_term}}</h1>
                <h3><a href="" class="text-primary"> ← Back To Products </a></h3>
                {% else %}
                <h1>All Products</h1>
                {% endif %}
            </div>
        </div>
</div>
</section>
<!-- ================ end banner area ================= -->

<div class="d-flex justify-content-center my-5">
  <form class="input-group w-50" action="{% url 'user:search' %}" method="post">
    {% csrf_token %}
    <input name="search_term" type="text" required class="form-control" aria-label="Text input with segmented dropdown button" placeholder="Search by product name.">
    <div class="input-group-append">
      <button type="submit" class="btn btn-outline-primary">Search</button>
    </div>
  </form>
</div>

<!-- ================ category section start ================= -->		  
<section class="section-margin--small mb-5">
<div class="container">
  <div class="row">
    <div class="col-xl-12 col-lg-10 col-md-7">
      <!-- Start Best Seller -->
      <section class="lattest-product-area pb-40 category-list">
        <div class="row">
          <!-- Start of Product Card -->
           {% for product in products %}
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="card text-center card-product">
              <div class="card-product__img">
                <img class="card-img" src="{{product.image.url}}" alt="Product image" height="250px" width="250px">
                <ul class="card-product__imgOverlay">
                  <li><a href="{% url 'user:add_to_cart' product.id %}"><button onclick="addedToCart()"><i class="ti-shopping-cart"></i></button></a></li>
                  <script>
                    function addedToCart(){
                      alert('This item was added to your cart')
                    }
                  </script>
                  <li><a href="{% url 'user:buy_now' product.id %}"><button onclick="buyNow()"><i class="ti-credit-card"></i></button></a></li>
                  <script>
                    function buyNow(){
                      alert('This will remove other items from your cart')
                    }
                  </script>
                </ul>
              </div>
              <div class="card-body">
                <a href="{% url 'user:category' product.category.id %}">{{product.category.name}}</a>
                <h4 class="card-product__title"><a href="{% url 'user:product' product.id %}">{{product.name}}</a></h4>
                <p class="card-product__price">${{product.price}}</p>
              </div>
            </div>
          </div>
          {% endfor %}
          <!-- End of Product Card -->
      </section>
      <!-- End Best Seller -->
    </div>
  </div>
</div>
</section>
<!-- ================ category section end ================= -->		  
{% endblock %}